### PR TITLE
A few changes for MSYS2

### LINKED ISSUE #156: MSYS build depends on libwinpthread-1.dll
### Describe your bug here. And how to reproduce it.

Since commit 3be6ece until most recent 3b7f2a6 the compilation using MSYS is broken.

For windows target the error is:
```cd tables; /usr/bin/env python3 compile_resources.py ../tables/zelda3.sfc
In file included from third_party/opus-1.3.1-stripped/pitch.h:42,
                 from third_party/opus-1.3.1-stripped/bands.c:44,
                 from third_party/opus-1.3.1-stripped/opus_decoder_amalgam.c:11:
third_party/opus-1.3.1-stripped/x86/pitch_sse.h:37:10: fatal error: config.h: No such file or directory
   37 | #include "config.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:17: third_party/opus-1.3.1-stripped/opus_decoder_amalgam.o] Error 1
make: *** Waiting for unfinished jobs....
```

for Switch Target the error is:
```c:/msys64/opt/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/12.1.0/../../../../aarch64-none-elf/bin/ld.exe: cannot find tracing.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /home/Impeeza/zelda3/platform/switch/zelda3.elf] Error 1
make: *** [Makefile:161: bin] Error 2
```

The packages installed are:
- git
- make
- mingw-w64-x86_64-gcc
- mingw-w64-x86_64-pkgconf
- mingw-w64-x86_64-python-yaml
- mingw-w64-x86_64-python3-pillow
- mingw-w64-x86_64-SDL2
- switch-dev
- switch-sdl2
- switch-tools

going back to commit ec08202 all compile right

Using TCC the file compiles OK.

### What is your build target?

Windows

### PR DESCRIPTION
**Pull request by hgdagon**
### Description
A few changes to make compilation in MSYS2 easier. No system opus required. Static executable. Should resolve #156 and #139 

### Will this Pull Request break anything? 
I've tested this in MSYS2, as well as arch in wsl, currently no Linux machine at hand.

### Suggested Testing Steps
Just run `make`

### CODE REVIEW

**Comment by impeeza** [comment]
Hi, what "No system opus required" means? thanks.

**Comment by hgdagon** [comment]
@impeeza In those issues I've linked there were solutions suggested, that involved linking external libopus, which is generally what I'd prefer, however the author of the repository seems to specifically want to use the included one. I decided not to go against that. In short, with the current solution you don't need libopus installed in msys2.

**Comment by impeeza** [comment]
This night will test the new commit, and if works fine will propose the add of Windres compilation of the rc file onto res one and the addition of the parameter to compiler to enable the creation of Zelda3.exe with icon on it :D

**Comment by impeeza** [comment]
Just compiled the commit e4febaf and works like a charm generate a new 4 MB Zelda3.exe with Icon and no dependencies at all, just copy to a new computer the Zelda3.exe, Zelda3.ini and zelda3_assets.dat and run without error messages.

Thanks a lot for your great effort, I am analyzing the new Makefile and start to learn a bit about make languaje 😸

**Pull request merged**
