### PR TITLE
For MSVS build, create output dir and copy .ini and /saves/ref

### PR DESCRIPTION
**Pull request by Nutzzz**

### CODE REVIEW

**Comment by snesrev** [comment]
Why not just copy the exe to the root directory instead?

**Comment by Nutzzz** [comment]
Because there's already stuff in the root. This places everything needed to deploy the game in its own location.

**Comment by snesrev** [comment]
I fixed so it chdirs to zelda3.ini in 6bd8b1185e7a9a1d80b4d9a10fbf6e04b767de4c

**Comment by Nutzzz** [comment]
Hm... this only deals with the situation where you're debugging the game from within VS or running it from the location it built in as a subdirectory of the source tree.  No matter how it's built, It's nice to be able to have everything you need to play the game in its own folder so that the files can then easily be moved elsewhere, i.e., decouple src and bin.

**Pull request closed without merging**
