### PR TITLE
Update zelda3.ini

### PR DESCRIPTION
**Pull request by JasonShearer**
### Description
Minor formatting fixes.

### Will this Pull Request break anything? 
No.

### Suggested Testing Steps
None.

### CODE REVIEW

**Comment by JasonShearer** [comment]
Should EnhancedMode7 and NoSpriteLimits be enabled by default?

**Comment by snesrev** [comment]
Why not?

**Comment by JasonShearer** [comment]
Just asking because they're enhancements, so the game's technically not vanilla out of the box.

**Comment by snesrev** [comment]
Please don't submit PR for 1 line whitespace...

**Pull request closed without merging**
