### PR TITLE
Add additional options to .ini file

### PR DESCRIPTION
**Pull request by Nutzzz**

### CODE REVIEW

**Comment by Nutzzz** [comment]
Like #29, this is a good candidate for an optional feature set in a config file

**Comment by snesrev** [comment]
Not sure I like this...

**Comment by Nutzzz** [comment]
Note: In addition to adding configuration settings to .ini file, this pull request also separates intermediate and output directory in Visual Studio, and automatically moves support files (saves/ref and zelda3.ini) to the output directory.

**Comment by Nutzzz** [comment]
I'm going to have to do a bit of a rewrite to match the method used in the new graphics section.

**Pull request merged**
