### PR TITLE
Add GitHub Actions Workflow to build

### PR DESCRIPTION
**Pull request by duhow**
Requires repository secret `ROM_URL` to extract assets used during build process.

### CODE REVIEW

**Comment by snesrev** [comment]
How can I use this? I can't published compiled binaries as they no longer depend on the rom.

**Comment by keatongreve** [comment]
@snesrev I believe once merged, it would (or can be configured to) run on all PRs to verify the changes compile on various platforms.

Unfortunately, I think having the build point to the ROM for extraction might be questionable. If we're going for compilation checks, we don't necessarily need to verify codegen, so perhaps we should build a script that generates headers and symbols to ensure the project compiles.

**Comment by duhow** [comment]
This Workflow purpose is to run the build steps on each PR and/or merge (push to master branch), so code will be **built** to ensure the process works, and the code is ok.
As the binary content might contain the original assets, this workflow is not meant to publish a binary as release or artifact.
If you need any additional steps to generate blank content, please indicate how to proceed.

**Comment by snesrev** [comment]
I merged it but I don't know GitHub so I don't know how to enable it. A script could easily be made to create all those arrays empty just to verify that it builds.

**Comment by snesrev** [comment]
We could also make a script that fills the arrays with pseudo-random data and then another script that could inject the rom data into the already built executable.

**Pull request merged**
